language: java

# -------------  ALL BRANCHES FIRE MVN INSTALL  ------------- ------------- --------
# MASTER: BUILD ON COMMIT (NO DEPLOY)
# +++++++++++++  STABLE AND TAGS FIRE DEPLOY    ++++++++++++++++++++++++++++++++++++
# TAGS: BUILD ON COMMIT + DEPLOY SONATYPE VERSION  RELEASE + GITHUB RELEASE
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Be aware when adding 'branch.only' they can exclude tags deployment is not fired
# 
# commande >>>>>>>>>> travis setup releases --com --force
# 
# -------------------------- ------------- ------------- ------------- ------------- 

matrix:
  include:
    - os: linux
      dist: xenial
cache:
    directories:
    - $HOME/.m2/repository
env:
  - JDK=amazon-corretto-11
  
jobs:
 include:
  - stage: amazon-corretto-11
    env: JDK=13
    script: source install-jdk.sh -F 13 && mvn -X --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=false -B -V

before_install:
  - export GPG_TTY=/dev/pts/4
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

install: skip 

#before_script: skip

#before_cache: skip

#after_success: skip

#after_failure: skip

#before_deploy: skip

#deploy: skip

#after_deploy: skip  
  
after_script:
  - echo JAVA_HOME = ${JAVA_HOME}
  - echo PATH = ${PATH}
  - ls ${JAVA_HOME}
  - java -version

