language: java

# -------------  ALL BRANCHES FIRE MVN INSTALL  ------------- ------------- --------
# MASTER: BUILD ON COMMIT (NO DEPLOY)
# +++++++++++++  STABLE AND TAGS FIRE DEPLOY    ++++++++++++++++++++++++++++++++++++
# TAGS: BUILD ON COMMIT + DEPLOY SONATYPE VERSION  RELEASE + GITHUB RELEASE
# +++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# Be aware when adding 'branch.only' they can exclude tags deployment is not fired
# 
# commande >>>>>>>>>> travis setup releases --com --force
# 
# -------------------------- ------------- ------------- ------------- ------------- 

matrix:
  include:
    - os: linux
      dist: xenial
      jdk: openjdk11
            
cache:
    directories:
    - $HOME/.m2/repository

before_script:
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh
	
jobs:
  include:
  	- stage:
  	env: JDK=11 
    script: source ./install-jdk.sh --feature 11

before_install:
    - export GPG_TTY=/dev/pts/4
    - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
    - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
    
script:
  - echo PATH = ${PATH}
  - echo $JAVA_HOME
  - java -version

install: 
    mvn -X --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=false -B -V
      
      
before_deploy:
    - mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
    - export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')

deploy: 
# 1. Trigger a version deploy when a commit on tag
# 2. And create a github release 
    - provider: script
      script: bash .travis/release.sh 
      skip_cleanup: true
      on:
        tags: true
        all_branches: true
        repo: jsoagger/jsoagger-core
        
    - provider: releases
      api_key:
        secure: XsFDpkc7zCogP3/n256Mr8eZ3n+gDooR10vkgl4G9HPQNeMGYV1flYnY7eKaoc9bQoIQTVojjf1rqGMdjrpKDadkGSIy9R9kMxENn/YBjnO46crYHYth3P33Nb0eqwyfqYc11eQXAifZY1fO1TSyLmwjI0sZyG0GqBphud9aPrbYXYa2JeqoyFQmw+NAd55GxBDHluzTOKtxTaCT2GkpVPPt/vPBLv7hNeDYkyWkT+EfBCzLtbW4CYn1sKhlkBv1ggoTfGFyfC62u9aOrEVQDBWGXea95jlzNaPJ2w3zj2JRb+jdRQPFi8eJDIkDfF7J+vUCIDP9cukdEk3RMcqtcgXvLWKvvgY4c1XqIS6zbX4b7gw8Oh/A0w0GKHpz2UVf2VrMzomIQkg/d9FZsmvtZ1W+XtBaHv4b0RHBDhLKTt+adrB1GUawwunkHaNr93Z35IbvAbWAGZfljn3nEjIKo4WLMaRNwfnAcHCOhZscAka3NKfNIJkYR4h76q+SLvZlf8trzy69jHtZCNF3u6Iuhxvhdvf1mvOFBMivdPoTIoxjrZZjbiRm0+p6QBOYoT+6UvdQrpUWuD4v7bBN9nwSj0KHKKEL9uYmqGz3bRtrQYnqJowY3kNZzhErmubsD3vmvgq+ouqPAJeswTB6W3sodeyEaXWrVeDQ+qZUmKWQqiM=
      skip_cleanup: true
      on:
          tags: true
          all_branches: true
          condition: $TRAVIS_OS_NAME = linux
          repo: jsoagger/jsoagger-core
 
